### ISSUE TITLE
Unable to open datbase file

### ISSUE THREAD

**Issue by 0323pin** [quantonganh/tetris-tui#1]
Hi,

NetBSD package maintainer here. Found this project yesterday and had a go packaging it for NetBSD today.

I have it ready but, I think it should create `~/.tetris` if the directory is non-existing. Else, the user gets:
```
Error: Custom { kind: Other, error: "SQLite error: unable to open database file: /home/pin/.tetris/high_scores.db" }
Exception: tetris-tui exited with 1
[tty 15]:1:1: tetris-tui
```

If the directory is there (even empty) the application will launch and work as expected.

![2023-09-14-120408_1366x768_scrot](https://github.com/quantonganh/tetris-tui/assets/90570748/10f47603-cf84-46e1-a5b7-6427cff7e887)

Would you like to push a fix for this or, should I just merge the package as is?
Thanks!

**Comment by quantonganh** [comment]
It has been fixed.
Could you please try again?

Thank you,

**Comment by 0323pin** [comment]
Yes, it's fine now. Thanks.
